name: todo
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=3.3.4 <4.0.0"

dependencies:
  provider: ^6.1.2
  equatable: ^2.0.5
  dio: ^5.4.3+1
  localstorage: ^5.0.0
  mockito: ^5.4.4
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true

  fonts:
    - family: Satoshi
      fonts:
        - asset: assets/fonts/satoshi/Satoshi-Light.otf
          weight: 300
        - asset: assets/fonts/satoshi/Satoshi-LightItalic.otf
          weight: 300
          style: italic
        - asset: assets/fonts/satoshi/Satoshi-Regular.otf
          weight: 400
        - asset: assets/fonts/satoshi/Satoshi-Italic.otf
          weight: 400
          style: italic
        - asset: assets/fonts/satoshi/Satoshi-Medium.otf
          weight: 500
        - asset: assets/fonts/satoshi/Satoshi-MediumItalic.otf
          weight: 500
          style: italic
        - asset: assets/fonts/satoshi/Satoshi-Bold.otf
          weight: 700
        - asset: assets/fonts/satoshi/Satoshi-BoldItalic.otf
          weight: 700
          style: italic
        - asset: assets/fonts/satoshi/Satoshi-Black.otf
          weight: 800
        - asset: assets/fonts/satoshi/Satoshi-BlackItalic.otf
          weight: 800
          style: italic
